version: '3.8'

services:
  web:
    build: .
    command: sh -c "python /upload_app/upload_app/manage.py migrate && python /upload_app/upload_app/manage.py runserver 0.0.0.0:8000 && celery -A upload_app/upload_app worker"
    container_name: django_upload_app
    volumes:
      - .:/upload_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://upload_files_admin:password@db:5432/upload_files
    depends_on:
      - db
      - rabbitmq
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/1_init_schema.sql

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
