# Generated by Django 4.2.5 on 2023-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/", verbose_name="Файл")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время загрузки"
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Файл обработан"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="File",
        ),
    ]
