# Generated by Django 4.2.5 on 2023-09-26 21:03

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0002_uploadfile_delete_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadfile",
            name="file",
            field=models.FileField(
                upload_to=files.models.upload_to, verbose_name="Файл"
            ),
        ),
    ]
